language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-silverstripe-theme' ]; then cd .. && eval "mv $currentfolder generator-silverstripe-theme" && cd generator-silverstripe-theme; fi

